/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    __asm ("SVC #8");
	for(;;);
}

__attribute__ ((naked)) void SCV_Handler (void)
{
	//1.
    __asm ("MRS R0, MSP");
    __asm ("B SVC Handler_c");
}

void SCV_Handler_C(uint32_t *pBaseOfStackFrame)
{
	//2. declare the return address by 2 to point to
	// opcode of the SVC instruction in the program memory
	pReturn_addr -= 2;

	//3. extract the SVC number (LS byte of the opcode )
	uint8_t svc_number = *pReturn_addr;

	printf("svc number is : %d", svc_number);
}
