/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// Load 2 values from memory , add them and store the result back to the memory using inline assembly statements.

int main(void)
{
#if 0
    __asm volatile("LDR R1,=#0x20001000");
    __asm volatile("LDR R1,=#0x20001004");
    __asm volatile("LDR R0,[R1]");
    __asm volatile("LDR R1,[R2]");
    __asm volatile("ADD R0,R0,R1");
    __asm volatile("STR R0,[R2]");
#endif

    int val = 50;
    __asm volatile ("MOV R0,%0": : "r"(val)); // constrain character + constrain string

    int control_reg;
    //read CONTROL register to control_reg
    __asm volatile ("MRS %0,CONTROL": "=r"(control_reg));


	for(;;);
}
