/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    // 1. enable all configurable exception like usage fault, mem manage fault, bus fault
	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;
	*pSHCSR |= (1<<16); // MEM MANAGE
	*pSHCSR |= (1<<17); // bus fault
	*pSHCSR |= (1<<18); // usage fault

	// 3. force the processor to execute some undefined instruction
	uint32_t *pSRAM = (uint32_t*)0x2001000;
	*pSRAM = 0xFFFFFFFF;

	void (*some_address) (void);

	some_address= (void*)0x2001001;

	some_address();


	for(;;);
}

// 2. implement the fault handler
void HardFault_Handler(void)
{
	printf("Exeption: Hardfault\n");
	while(10);
}

void MemManage_Handler(void)
{
	printf("Exeption: MemManage\n");
	while(10);
}

void BusFault_Handler(void)
{
	printf("Exeption: BusFault\n");
	while(10);
}

void UsageFault_Handler(void)
{
	printf("Exeption: UsageFault\n");
	while(10);
}

